# Generated by Django 3.0.5 on 2020-12-27 01:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cake_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gift_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twin',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='twin',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twin',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='twin',
            name='cake_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=None, size=None),
        ),
        migrations.AddField(
            model_name='twin',
            name='gift_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=None, size=None),
        ),
        migrations.AddField(
            model_name='twin',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
