# Generated by Django 3.0.5 on 2021-01-11 22:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twin',
            name='cake_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='twin',
            name='gift_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=list, size=None),
        ),
    ]
