# Generated by Django 3.0.5 on 2021-01-01 02:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201231_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='twin',
            name='match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255, null=True, unique=True), default=None, size=None),
        ),
    ]
