# Generated by Django 3.0.5 on 2021-01-02 01:59

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_twin_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='twin',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(null=True, upload_to=api.models.upload_path), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='twin',
            name='match',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255, null=True, unique=True), default=list, size=None),
        ),
    ]
