# Generated by Django 3.0.5 on 2021-01-02 02:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210101_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twin',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=api.models.upload_path)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Twin')),
            ],
        ),
    ]
