# Generated by Django 3.0.5 on 2021-01-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210101_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
